<div id="generator_left">
    <h1>
        <?= $title ?>:
        <?php if ($workout) { ?>
            <?= $workout['title'] ?>
        <?php } ?>
    </h1>

    <?php //print_r($workout); ?>
    <?php if ($workout) { ?>
        <?php if ($workout['created'] == 'false') { ?>
            <p>This workout has not been created yet. Please complete any workouts before this one then this workout will be
                autogenerated.</p>
        <?php } elseif ($workout['completed'] == 'false' && $workout['workout_date'] <= date('Y-m-d')) { ?>
            <p>This workout has not been completed yet. If you have completed it, please enter your statistics in the
                corresponding exercises.</p>
        <?php } ?>
        <?php if ($workout['created'] == 'true') { ?>
            <p><a href="#" class="expand_all">Expand All</a> | <a target="_blank"
                    href="/member/print_log_book<?php if ($this->uri->segment(3) != '') { ?>/<?= $this->uri->segment(3) ?>/<?= $this->uri->segment(4) ?>/<?= $this->uri->segment(5) ?><?php } ?>">Printer
                    Friendly Version</a></p>
            <form action="/member/save_logbook_stats" method="post">
                <input type="hidden" name="uw_id" value="<?= $workout['workout_id'] ?>" />
                <input type="hidden" name="workout_date" value="<?= $workout['workout_date'] ?>" />
                <ul id="workout_logbook">
                    <?
                    foreach ($workout['sections'] as $section) {
                        ?>
                        <li><a href="#"
                                class="<?php if ($section['title'] == 'Rest') { ?>section_rest<?php } else { ?>section_title<?php } ?> off"><?= $section['title'] ?><?php if ($section['section_rest'] != '' && $section['section_rest'] != 0) { ?> -
                                    <?= secToMinute($section['section_rest']) ?>            <?php } ?></a>
                            <?php if (isset($section['exercises'])) { ?>
                                <ul class="section">
                                    <?php foreach ($section['exercises'] as $exercise) {
                                        ?>
                                        <li><a href="#" class="type_title off"><span>
                                                    <?= $exercise['type_title'] ?>
                                                </span></a>
                                            <ul class="type">
                                                <li class="exercise_type">
                                                    <input type="hidden" name="uwe[<?= $exercise['uwe_id'] ?>][uwe_id]"
                                                        value="<?= $exercise['uwe_id'] ?>" />

                                                    <table width="100%" cellspacing="0" cellpadding="0">
                                                        <thead>
                                                            <tr>
                                                                <th class="left"><a href="/member/popup_video/<?= $exercise['id'] ?>"
                                                                        class="play-exercise"><?= $exercise['title'] ?></a></th>
                                                                <th>Set</th>
                                                                <th>
                                                                    <?php if ($exercise['set_type'] == 'sets_reps') { ?>Reps
                                                                    <?php } elseif ($exercise['set_type'] == 'sets_time') { ?>Time
                                                                    <?php } ?>
                                                                </th>
                                                                <th>Rest</th>
                                                                <th>
                                                                    <?php if ($exercise['set_type'] == 'sets_reps') { ?>Reps
                                                                    <?php } elseif ($exercise['set_type'] == 'sets_time') { ?>Time
                                                                    <?php } ?>
                                                                </th>
                                                                <th class="right">Weight</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?
                                                            $ex_sets = explode('|', $exercise['sets']);
                                                            $ex_reps = explode('|', $exercise['reps']);
                                                            $ex_rest = explode('|', $exercise['rest']);
                                                            $ex_weight = explode('|', $exercise['weight']);
                                                            $ex_time = explode('|', $exercise['time']);
                                                            foreach ($ex_sets as $index => $set) {
                                                                $save_stats = mysql_query("SELECT * FROM user_workout_stats WHERE uwe_id = '" . $exercise['uwe_id'] . "' AND user_workout_stats.set = '" . $set . "'");
                                                                if ($previous_stats = mysql_fetch_assoc($save_stats)) {
                                                                    $previous = true;
                                                                    $reps = $previous_stats['reps'];
                                                                    $weight = $previous_stats['weight'];
                                                                    $time = $previous_stats['time'];
                                                                    $difficulty = $previous_stats['difficulty'];
                                                                } else {
                                                                    $previous = false;
                                                                    $reps = $ex_reps[$index];
                                                                    if (isset($ex_weight[$index])) {
                                                                        $weight = $ex_weight[$index];
                                                                    }
                                                                    if (isset($ex_time[$index])) {
                                                                        $time = $ex_time[$index];
                                                                    }
                                                                    $difficulty = 3;
                                                                }
                                                                $rest = $ex_rest[$index]; ?>
                                                                <tr <?php if ($set == count($ex_sets)) { ?> class="bottom" <?php } ?>>
                                                                    <?php if ($set == 1) { ?><td class="left bottom"
                                                                            rowspan="<?= count($ex_sets) ?>">&nbsp;</td>
                                                                    <?php } ?>
                                                                    <td>
                                                                        <?= $set ?><input name="uwe[<?= $exercise['uwe_id'] ?>][sets][]"
                                                                            type="hidden" value="<?= $set ?>" />
                                                                    </td>
                                                                    <td>
                                                                        <?php if ($exercise['set_type'] == 'sets_reps') { ?>
                                                                            <?= $ex_reps[$index] ?>
                                                                        <?php } else { ?>
                                                                            <?= secToMinute($ex_time[$index]) ?>
                                                                        <?php } ?>
                                                                    </td>
                                                                    <td class="right">
                                                                        <?= $ex_rest[$index] ?>
                                                                    </td>
                                                                    <td>
                                                                        <?php if ($exercise['set_type'] == 'sets_reps') { ?>
                                                                            <select name="uwe[<?= $exercise['uwe_id'] ?>][reps][]">
                                                                                <?php for ($x = 1; $x <= 30; $x++) { ?>
                                                                                    <option value="<?= $x ?>" <?php if ($exercise['reps'] == $x) { ?>
                                                                                            selected="selected" <?php } ?>><?= $x ?></option>
                                                                                <?php } ?>
                                                                            </select>
                                                                        <?php } elseif ($exercise['set_type'] == 'sets_time') { ?>
                                                                            <select name="uwe[<?= $exercise['uwe_id'] ?>][time][]" class="time">
                                                                                <?php for ($x = 15; $x <= 300; $x += 15) { ?>
                                                                                    <option value="<?= $x ?>" <?php if ($exercise['time'] == $x) { ?>
                                                                                            selected="selected" <?php } ?>><?= secToMinute($x) ?></option>
                                                                                <?php } ?>
                                                                            </select>
                                                                        <?php } ?>
                                                                    </td>
                                                                    <td class="right">
                                                                        <?php if ($exercise['weight_option'] == 'weighted') { ?>
                                                                            <input type="text" name="uwe[<?= $exercise['uwe_id'] ?>][weight][]"
                                                                                class="weight" value="<?= $weight ?>" /> lbs.
                                                                        <?php } elseif ($exercise['weight_option'] == 'bodyweight') { ?>
                                                                            Body Weight
                                                                        <?php } ?>
                                                                    </td>
                                                                </tr>
                                                            <?php } ?>
                                                        <tbody class="spacer">
                                                            <tr>
                                                                <td colspan="6">&nbsp;</td>
                                                            </tr>
                                                        </tbody>
                                                        <tbody class="footer">
                                                            <tr>
                                                                <td colspan="4" class="left">
                                                                    <strong>COMMENTS</strong>
                                                                    <input type="radio" name="uwe[<?= $exercise['uwe_id'] ?>][difficulty]"
                                                                        value="1" <?php if ($difficulty == 1) { ?> checked="checked" <?php } ?> /> easy
                                                                    <input type="radio" name="uwe[<?= $exercise['uwe_id'] ?>][difficulty]"
                                                                        value="2" <?php if ($difficulty == 2) { ?> checked="checked" <?php } ?> /> moderate
                                                                    <input type="radio" name="uwe[<?= $exercise['uwe_id'] ?>][difficulty]"
                                                                        value="3" <?php if ($difficulty == 3) { ?> checked="checked" <?php } ?> /> difficult
                                                                    <input type="radio" name="uwe[<?= $exercise['uwe_id'] ?>][difficulty]"
                                                                        value="4" <?php if ($difficulty == 4) { ?> checked="checked" <?php } ?> /> impossible
                                                                </td>
                                                                <td colspan="2" class="right">
                                                                    <!--<strong>SHARE</strong>-->
                                                                    <!--<input type="submit" name="submit" value="<?php if ($previous) { ?>UPDATE STATS<?php } else { ?>SAVE STATS<?php } ?>" />-->
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </li>
                                            </ul>
                                        </li>
                                    <?
                                    } ?>
                                </ul>
                            <?php } ?>
                        </li>
                    <?
                    }
                    ?>
                </ul>
                <?

                if ($workout['completed'] == 'false' && $workout['workout_date'] <= date('Y-m-d')) { ?>
                    <input type="submit" class="large_submit" value="Complete Workout" />
                </form>
            <?php }
        }


        ?>

        <h1>Video of Entire Workout</h1>
        <div id="entire_workout_video">

        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                jwplayer("entire_workout_video").setup({
                    // 'playlist': '/member/workout_playlist/<?= $workout['workout_id'] ?>',
                    'playlist': [
                        <?php foreach ($workout['sections'] as $section) {
                            if (isset($section['exercises'])) {
                                foreach ($section['exercises'] as $exercise) { ?>
                                            { file: "<?= $exercise['mobile_video'] ?>" },
                                <? }
                            }
                        } ?>
                    ],
                    height: 299,
                    'provider': 'video',
                    'playlist.position': 'right',
                    'playlist.size': '320',
                    'repeat': 'list'
                });
            });
        </script>

    <?
    } else { ?>
        <p><strong>You had no workout today</strong></p>
    <?php } ?>
</div>

<div id="generator_right">
    <h2 class="library_header">ARCHIVED WORKOUTS</h2>
    <p class="smaller">Select a month to view past workouts and comments.</p>
    <ul id="archive_logbook">
        <?php if ($past_workouts) {
            $current_month = '';
            $current_year = '';
            foreach ($past_workouts as $workout) {
                if ($current_month != date('F', strtotime($workout->workout_date)) || $current_year != date('Y', strtotime($workout->workout_date))) {
                    if ($current_month != '') { ?>
                    </ul>
                    </li>
                <?php }
                    $current_month = date('F', strtotime($workout->workout_date));
                    $current_year = date('Y', strtotime($workout->workout_date));
                    ?>
                <li><a href="#" class="month_title off">
                        <?= $current_month ?>
                        <?= $current_year ?>
                    </a>
                    <ul class="month">
                    <?
                }
                ?>
                    <li><a class="day" href="/member/log_book/<?= date('Y/m/d', strtotime($workout->workout_date)) ?>"><?= date('l jS', strtotime($workout->workout_date)) ?></a></li>
                <?
            }
        } ?>
        </ul>

</div>